const SUPABASE_URL='https://zylbttyclmkzkrlpdyzw.supabase.co';
const SUPABASE_KEY='sb_publishable_tMGexHiobGnYwlMLo3Gjmg_yaEmEzk9';
const TABLE='tasks';
const BUILD='v0.7.0-dev';
const LAST_SYNC_KEY='wtt_last_synced_at';
const AUTO_ARCHIVE_KEY='wtt_auto_archive';
const PROXY_KEY='wtt_proxy_url';
let tasks=[],archiveData=[],filter='all',sortMode='default',category='all',newTaskCat='work';
let activeTaskId=null,pendingScheduleDate='',pendingPriority='medium',pendingDeleteId=null,tagHighlightIndex=-1;
let settingsOpen=false,archiveOpen=false,calOpen=false,reportOpen=false,reportType='daily',reportText='',ptrStartY=0,ptrActive=false,syncTimer=null;
let client=null,user=null,channel=null,lastCloudError='',gesture=null,ignoreTaskTapUntil=0,calAnchor=new Date();
const $=id=>document.getElementById(id);
const now=()=>Date.now();
const key=v=>{if(!v)return'';const d=v instanceof Date?v:new Date(v);if(Number.isNaN(d.getTime()))return'';return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const today=()=>key(new Date());
const tomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);return key(d)};
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const id=()=>window.crypto?.randomUUID?window.crypto.randomUUID():`task-${Date.now()}-${Math.random().toString(16).slice(2,8)}`;
const fmtTime=v=>{if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})};
const fmtDate=v=>{if(!v)return'Unscheduled';return new Date(`${v}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})};
function indicator(msg,tone='ok'){const el=$('syncIndicator');if(!el)return;el.textContent=msg;el.style.color=tone==='error'?'#ff8a8a':tone==='warn'?'#f5a623':'#d7e0ff';el.style.borderTopColor=tone==='error'?'#5c1f1f':tone==='warn'?'#5c4b1f':'rgba(124,156,255,.24)';el.style.background=tone==='error'?'rgba(38,14,14,.97)':tone==='warn'?'rgba(38,27,14,.97)':'rgba(13,13,13,.94)';el.classList.add('show');el.style.transform='translateY(0)';clearTimeout(indicator.t);indicator.t=setTimeout(()=>{el.classList.remove('show');el.style.transform='translateY(100%)'},1800)}
function syncStamp(){localStorage.setItem(LAST_SYNC_KEY,String(now()));refreshLastSyncUI()}
function refreshLastSyncUI(){const el=$('lastSyncText');if(!el)return;const raw=Number(localStorage.getItem(LAST_SYNC_KEY)||0);el.textContent=!raw?(lastCloudError?`Cloud error: ${lastCloudError}`:'Last synced: not yet'):`Last synced: ${fmtTime(raw)}`}
const prefs=()=>({autoArchive:localStorage.getItem(AUTO_ARCHIVE_KEY)==='1'});
function renderWorkflowSettings(){const t=$('autoArchiveToggle');if(t)t.classList.toggle('on',prefs().autoArchive)}
function toggleAutoArchive(){localStorage.setItem(AUTO_ARCHIVE_KEY,prefs().autoArchive?'0':'1');renderWorkflowSettings()}
function saveProxyUrl(){localStorage.setItem(PROXY_KEY,$('proxyUrlInput')?.value?.trim()||'');indicator('Saved')}
function initAIStatus(){const dot=$('aiStatusDot'),txt=$('aiStatusText'),ai=$('aiDot');if(dot)dot.classList.remove('on');if(txt)txt.textContent='Non-core features paused in dev rebuild';if(ai)ai.style.display='none'}
function disableNonCoreFeatures(){if($('notifSettingsRow'))$('notifSettingsRow').innerHTML='<div class="settings-hint">Notifications come back after sync parity.</div>';if($('notifTimesRow'))$('notifTimesRow').style.display='none';const b=$('btnPolishNote');if(b){b.textContent='Unavailable in dev';b.disabled=true;b.style.opacity='0.45'}}
function toggleSettings(){settingsOpen=!settingsOpen;$('settingsPanel')?.classList.toggle('open',settingsOpen);$('settingsBtn')?.classList.toggle('active',settingsOpen)}
function toggleCalendar(force){calOpen=typeof force==='boolean'?force:!calOpen;$('calOverlay')?.classList.toggle('open',calOpen);$('calBtn')?.classList.toggle('active',calOpen);if(calOpen)renderCalendar()}
function toggleArchive(force){archiveOpen=typeof force==='boolean'?force:!archiveOpen;$('archiveOverlay')?.classList.toggle('open',archiveOpen);if(archiveOpen)renderArchive()}
function getWeekWindow(){const d=new Date();d.setHours(0,0,0,0);const dow=d.getDay();const start=new Date(d);start.setDate(d.getDate()-(dow===0?6:dow-1));const end=new Date(start);end.setDate(start.getDate()+6+(dow===0?7:0));return{start:key(start),end:key(end)}}
function weekLabel(){const {start,end}=getWeekWindow();const s=new Date(`${start}T00:00:00`),e=new Date(`${end}T00:00:00`);return `${s.toLocaleDateString(undefined,{month:'short',day:'numeric'})} - ${e.toLocaleDateString(undefined,{month:'short',day:'numeric'})}`}
function compactWeekLabel(){const {start,end}=getWeekWindow();const s=new Date(`${start}T00:00:00`),e=new Date(`${end}T00:00:00`);return `${s.toLocaleDateString(undefined,{month:'short',day:'numeric'})} - ${e.toLocaleDateString(undefined,{month:'short',day:'numeric'})}`}
function reportPool(){return [...tasks,...archiveData].filter(t=>!t.deletedAt&&t.category==='work')}
function doneDate(t){return t.completedAt?key(t.completedAt):(t.archivedDate||'')}
function inRange(d,start,end){return !!d&&d>=start&&d<=end}
function taskLine(t,{includeTag=false}={}){const bits=[t.text];if(includeTag&&t.tag)bits.push(`#${t.tag}`);if(t.scheduledDate)bits.push(`due ${fmtDate(t.scheduledDate)}`);if(t.blocked)bits.push('BLOCKED');return bits.join(' ')}
function reportSection(title,items,fallback){const html=items.length?items.map(t=>`<div class=\"report-row\"><span class=\"report-bullet\">•</span><span>${esc(taskLine(t))}</span></div>`).join(''):`<div class=\"report-row\"><span class=\"report-bullet\">•</span><span>${esc(fallback)}</span></div>`;const md=items.length?items.map(t=>`- ${taskLine(t)}`).join('\\n'):`- ${fallback}`;return{html:`<div class=\"report-section\"><div class=\"report-section-title\">${esc(title)}</div><div class=\"report-content\">${html}</div></div>`,md:`## ${title}\\n${md}`} }
function groupByTag(items){const map=new Map();items.forEach(t=>{const tag=(t.tag||'General').trim()||'General';if(!map.has(tag))map.set(tag,[]);map.get(tag).push(t)});return [...map.entries()].sort((a,b)=>a[0].localeCompare(b[0]))}
function taggedReportSection(title,items,fallback){if(!items.length){return{html:`<div class=\"report-section\"><div class=\"report-section-title\">${esc(title)}</div><div class=\"report-content\"><div class=\"report-row\"><span class=\"report-bullet\">•</span><span>${esc(fallback)}</span></div></div></div>`,md:`## ${title}\\n- ${fallback}`}}const groups=groupByTag(items);const html=`<div class=\"report-section\"><div class=\"report-section-title\">${esc(title)}</div><div class=\"report-content\">${groups.map(([tag,list])=>`<div class=\"weekly-group\"><div class=\"weekly-group-header\"><span class=\"weekly-tag-label\">#${esc(tag)}</span><div class=\"weekly-progress-bar\"><div class=\"weekly-progress-fill\" style=\"width:100%;background:rgba(124,156,255,.55)\"></div></div><span class=\"weekly-status-text\" style=\"color:var(--work)\">${list.length}</span></div>${list.map(t=>`<div class=\"report-row\"><span class=\"report-bullet\">•</span><span>${esc(taskLine(t))}</span></div>`).join('')}</div>`).join('')}</div></div>`;const md=`## ${title}\\n${groups.map(([tag,list])=>`### ${tag}\\n${list.map(t=>`- ${taskLine(t)}`).join('\\n')}`).join('\\n\\n')}`;return{html,md}}
function toggleReport(event){const overlay=$('reportOverlay');if(!overlay)return;if(overlay.classList.contains('open')){closeReport();return}if(event){const btn=(event.target.closest('button')||event.target);const rect=btn.getBoundingClientRect();const top=rect.bottom+8;overlay.style.setProperty('--report-top',`${top}px`);$('reportCard').style.top=`${top}px`}reportOpen=true;overlay.classList.add('open');$('reportBtn')?.classList.add('active');document.body.style.overflow='hidden';setReportType(reportType)}
function closeReport(){reportOpen=false;$('reportOverlay')?.classList.remove('open');$('reportBtn')?.classList.remove('active');document.body.style.overflow=''}
function handleReportOverlayClick(e){if(e.target?.id==='reportOverlay')closeReport()}
function setReportType(type){reportType=type==='weekly'?'weekly':'daily';$('typeBtnDaily')?.classList.toggle('active',reportType==='daily');$('typeBtnWeekly')?.classList.toggle('active',reportType==='weekly');$('reportDate').textContent=reportType==='daily'?new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}):weekLabel();$('reportBody').innerHTML=`<div class=\"report-generating\">Tap Generate to create your ${reportType} report</div>`;$('copyReportBtn').style.display='none';reportText=''}
function toggleAI(){indicator('AI report disabled in dev','warn')}
function generateDailyReport(){const tk=today(),tmk=tomorrow(),pool=reportPool();const completed=pool.filter(t=>doneDate(t)===tk).sort((a,b)=>(b.completedAt||b.archivedAt||0)-(a.completedAt||a.archivedAt||0));const blocked=tasks.filter(t=>t.category==='work'&&t.blocked).sort(cmp);const tomorrowTasks=tasks.filter(t=>t.category==='work'&&!t.done&&!t.blocked&&t.scheduledDate===tmk).sort(cmp);const sections=[reportSection('Completed Today',completed,'No work tasks completed today.'),reportSection('Blockers',blocked,'No blockers reported.'),reportSection('Tomorrow',tomorrowTasks,'No work tasks scheduled for tomorrow.')];reportText=`# Daily Work Update\\n${new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}\\n\\n${sections.map(s=>s.md).join('\\n\\n')}`;$('reportBody').innerHTML=sections.map(s=>s.html).join('');$('copyReportBtn').style.display='inline-block'}
function generateWeeklyReport(){const {start,end}=getWeekWindow(),pool=reportPool();const completed=pool.filter(t=>inRange(doneDate(t),start,end)).sort((a,b)=>(b.completedAt||b.archivedAt||0)-(a.completedAt||a.archivedAt||0));const open=tasks.filter(t=>t.category==='work'&&!t.done&&inRange(t.scheduledDate||today(),start,end)).sort(cmp);const tomorrowTasks=tasks.filter(t=>t.category==='work'&&!t.done&&!t.blocked&&t.scheduledDate===tomorrow()).sort(cmp);const sections=[taggedReportSection('Completed This Week',completed,'No completed work tasks logged this week.'),taggedReportSection('Open This Week',open,'No open work tasks this week.'),reportSection('Tomorrow',tomorrowTasks,'No work tasks scheduled for tomorrow.')];reportText=`# Weekly Work Update\\n${weekLabel()}\\n\\n${sections.map(s=>s.md).join('\\n\\n')}`;$('reportBody').innerHTML=sections.map(s=>s.html).join('');$('copyReportBtn').style.display='inline-block'}
function runReport(){if(!user&&!tasks.length&&!archiveData.length){$('reportBody').innerHTML='<div class=\"report-generating\">Sign in to generate reports from cloud task history.</div>';return}if(reportType==='weekly')generateWeeklyReport();else generateDailyReport()}
function copyReport(){if(!reportText)return;navigator.clipboard?.writeText(reportText).then(()=>indicator('Report copied')).catch(()=>indicator('Copy failed','error'))}
function polishNotes(){indicator('Note polish is disabled in dev','warn')}
function requestNotifPermission(){indicator('Notifications are disabled in dev','warn')}
function toggleNotifTime(){}
function saveNotifSettings(){}
function initNotifications(){}
function updateNotifUI(){}
function loadNotifSettings(){}
function scheduleNotifications(){}
function initATH(){const st=window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone;const dismissed=localStorage.getItem('wtt_ath_dismissed');$('athBanner').style.display=!st&&!dismissed?'flex':'none'}
function dismissATH(){$('athBanner').style.display='none';localStorage.setItem('wtt_ath_dismissed','1')}
function sb(){if(client)return client;client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return client}
function rowTask(r){return{id:String(r.id),userId:r.user_id||'',ownerEmail:r.owner_email||'',text:r.text||'',category:r.category||'work',done:!!r.done,blocked:!!r.blocked,priority:r.priority||'medium',scheduledDate:r.scheduled_date||'',notes:r.notes||'',createdAt:Number(r.created_at)||now(),completedAt:r.completed_at?Number(r.completed_at):null,updatedAt:Number(r.updated_at)||now(),tag:r.tag||'',archivedAt:r.archived_at?Number(r.archived_at):null,archivedDate:r.archived_date||'',deletedAt:r.deleted_at?Number(r.deleted_at):null}}
function taskRow(t){return{id:t.id,user_id:t.userId||user.id,owner_email:t.ownerEmail||user.email||'',text:t.text,category:t.category,done:!!t.done,blocked:!!t.blocked,priority:t.priority,scheduled_date:t.scheduledDate||null,notes:t.notes||'',created_at:t.createdAt||now(),completed_at:t.completedAt||null,updated_at:t.updatedAt||now(),tag:t.tag||null,sort_order:null,archived_at:t.archivedAt||null,archived_date:t.archivedDate||null,deleted_at:t.deletedAt||null}}
function cmp(a,b){if(sortMode==='priority'){const r={high:0,medium:1,low:2};const d=(r[a.priority]??9)-(r[b.priority]??9);if(d)return d}if(sortMode==='date'){const d=(a.scheduledDate||'9999-12-31').localeCompare(b.scheduledDate||'9999-12-31');if(d)return d}if(a.done!==b.done)return a.done?1:-1;if(a.blocked!==b.blocked)return a.blocked?1:-1;const d=(a.scheduledDate||'9999-12-31').localeCompare(b.scheduledDate||'9999-12-31');if(d)return d;return (b.updatedAt||0)-(a.updatedAt||0)}
function applyRows(rows){const all=rows.map(rowTask);tasks=all.filter(t=>!t.deletedAt&&!t.archivedAt).sort(cmp);archiveData=all.filter(t=>!t.deletedAt&&t.archivedAt).sort((a,b)=>(b.archivedAt||0)-(a.archivedAt||0));render();if(archiveOpen)renderArchive();if(calOpen)renderCalendar()}
async function fetchRows(){if(!user)return[];const {data,error}=await sb().from(TABLE).select('*').order('updated_at',{ascending:false});if(error)throw error;return data||[]}
async function refreshFromCloud(reason='refresh'){if(!user){tasks=[];archiveData=[];render();return}const rows=await fetchRows();lastCloudError='';applyRows(rows);syncStamp();if(reason!=='realtime')indicator('Cloud synced');renderSyncSettings()}
async function upsertRows(rows){if(!user)throw new Error('Sign in required');const {error}=await sb().from(TABLE).upsert(rows.map(taskRow),{onConflict:'id'});if(error)throw error;syncStamp()}
function cloud(action='save changes'){if(user)return true;indicator(`Sign in to ${action}`,'warn');if(!settingsOpen)toggleSettings();return false}
function renderSyncSettings(){const row=$('syncSettingsRow');if(!row)return;if(!user){row.innerHTML='<div class="sync-status"><div class="sync-dot"></div><span>Signed out. Cloud tasks stay read-only until you sign in.</span></div><button class="google-btn" id="syncSigninBtn" type="button">Sign in with Google</button>';$('syncSigninBtn')?.addEventListener('click',supabaseSignIn);refreshLastSyncUI();return}const err=lastCloudError?`<div class="settings-hint" style="width:100%;color:#ff8a8a">${esc(lastCloudError)}</div>`:'';row.innerHTML=`<div class="sync-status"><div class="sync-dot on"></div><span>${esc(user.email||'')}</span></div><button class="btn-sm green" id="syncRefreshBtn" type="button">Refresh</button><button class="btn-signout" id="syncSignoutBtn" type="button">Sign out</button>${err}`;$('syncRefreshBtn')?.addEventListener('click',()=>refreshFromCloud('manual').catch(handleCloudError));$('syncSignoutBtn')?.addEventListener('click',supabaseSignOut);refreshLastSyncUI()}
function handleCloudError(error){lastCloudError=error?.message||'Cloud sync failed';refreshLastSyncUI();renderSyncSettings();indicator(lastCloudError,'error')}
async function supabaseSignIn(){const {error}=await sb().auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.href}});if(error)handleCloudError(error)}
async function supabaseSignOut(){if(!client)return;const {error}=await client.auth.signOut();if(error){handleCloudError(error);return}user=null;tasks=[];archiveData=[];lastCloudError='';if(channel){client.removeChannel(channel);channel=null}renderSyncSettings();render()}
function schedulePeriodicSync(){clearInterval(syncTimer);syncTimer=setInterval(()=>{if(user&&document.visibilityState==='visible')refreshFromCloud('interval').catch(handleCloudError)},45000)}
async function syncNow(){if(cloud('refresh cloud data'))await refreshFromCloud('manual').catch(handleCloudError)}
function subRealtime(){if(!client||!user)return;if(channel)client.removeChannel(channel);channel=client.channel(`dev-${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:TABLE},()=>refreshFromCloud('realtime').catch(handleCloudError)).subscribe()}
async function initSupabaseSync(){try{const {data,error}=await sb().auth.getSession();if(error)throw error;user=data.session?.user||null;renderSyncSettings();if(user){subRealtime();await refreshFromCloud('startup')}else render();client.auth.onAuthStateChange((_e,session)=>{user=session?.user||null;lastCloudError='';renderSyncSettings();if(user){subRealtime();refreshFromCloud('auth').catch(handleCloudError)}else{tasks=[];archiveData=[];render()}})}catch(error){handleCloudError(error);render()}}
function visibleTasks(){return tasks.filter(t=>category==='all'||t.category===category).filter(t=>filter==='active'?!t.done&&!t.blocked:filter==='done'?t.done:filter==='blocked'?t.blocked:true).slice().sort(cmp)}
function groupKey(t){if(!t.scheduledDate)return'unscheduled';if(t.scheduledDate<today())return'overdue';if(t.scheduledDate===today())return'today';if(t.scheduledDate===tomorrow())return'tomorrow';return'future'}
function taskMarkup(t){const badges=[`<span class="cat-badge ${esc(t.category)}">${esc(t.category)}</span>`,`<span class="priority-badge ${esc(t.priority)}">${esc(t.priority)}</span>`];if(t.tag)badges.push(`<span class="task-tag-badge">#${esc(t.tag)}</span>`);if(t.blocked)badges.push('<span class="blocked-badge">Blocked</span>');if(t.scheduledDate)badges.push(`<span class="task-tag-badge">${esc(fmtDate(t.scheduledDate))}</span>`);return `<div class="task-item ${t.done?'done':''} ${t.blocked?'blocked':''} cat-${esc(t.category)}" data-task-id="${esc(t.id)}"><div class="task-body"><div class="task-text ${t.notes?'has-notes':t.category==='work'?'no-notes-work':''}">${esc(t.text)}</div><div class="task-meta">${badges.join('')}</div></div></div>`}
function renderEmpty(list){const e=$('emptyState');if(!e)return;if(!user){e.style.display='block';e.innerHTML='<div class="empty-icon">+</div><div>Sign in with Google to use cloud tasks.</div>';return}if(lastCloudError){e.style.display='block';e.innerHTML=`<div class="empty-icon">!</div><div>${esc(lastCloudError)}</div>`;return}e.style.display=list.length?'none':'block';if(!list.length)e.innerHTML='<div class="empty-icon">*</div><div>Nothing here yet.</div>'}
function render(){const list=visibleTasks();$('count-all').textContent=tasks.length;$('count-work').textContent=tasks.filter(t=>t.category==='work').length;$('count-personal').textContent=tasks.filter(t=>t.category==='personal').length;$('remaining').textContent=tasks.filter(t=>!t.done&&!t.blocked).length;const clear=$('clearBtn'),doneCount=tasks.filter(t=>t.done).length;if(clear){clear.style.display=doneCount?'inline-flex':'none';clear.textContent=`Archive completed (${doneCount})`}const groups={overdue:[],today:[],tomorrow:[],future:[],unscheduled:[]};list.forEach(t=>groups[groupKey(t)].push(t));const labels={overdue:'Overdue',today:'Today',tomorrow:'Tomorrow',future:'Upcoming',unscheduled:'Unscheduled'};const banner=`<div class="week-banner"><div class="week-banner-copy"><span class="week-banner-label">Current Window</span><span class="week-banner-range">${esc(compactWeekLabel())}</span></div><button class="week-banner-btn ${reportOpen?'active':''}" id="reportBtn" onclick="toggleReport(event)">Report</button></div>`;$('taskListContainer').innerHTML=banner+Object.entries(groups).filter(([,v])=>v.length).map(([k,v])=>`<div class="day-group"><div class="day-group-header"><div class="day-group-label ${k}">${labels[k]}</div><div class="day-group-line"></div><div class="day-group-count">${v.length}</div></div><div class="task-list">${v.map(taskMarkup).join('')}</div></div>`).join('');renderEmpty(list);bindTaskItems()}
function setCategory(next,btn){category=next;document.querySelectorAll('.cat-tab').forEach(t=>t.classList.toggle('active',t===btn||t.dataset.cat===next));render()}
function selectCat(next){newTaskCat=next;$('selWork')?.classList.toggle('active',next==='work');$('selPersonal')?.classList.toggle('active',next==='personal')}
function setFilterFromSelect(v){filter=v||'all';render()}
function setSortFromSelect(v){sortMode=v||'default';render()}
function taskById(taskId){return tasks.find(t=>t.id===taskId)||archiveData.find(t=>t.id===taskId)||null}
function openModal(taskId){const isNew=taskId==='__new__';const t=isNew?{id:'__new__',text:$('taskInput')?.value.trim()||'',category:newTaskCat,priority:'medium',scheduledDate:'',notes:'',tag:'',createdAt:now(),updatedAt:null,blocked:false}:taskById(taskId);if(!t)return;activeTaskId=t.id;pendingScheduleDate=t.scheduledDate||'';pendingPriority=t.priority||'medium';$('modalTitleInput').value=t.text||'';$('tagInput').value=t.tag||'';$('notesArea').value=t.notes||'';$('modalSubtitle').textContent=isNew?`${t.category==='personal'?'Personal':'Work'} task · choose a date to create`:t.category==='personal'?'Personal task':'Work task';$('modalTimestamps').textContent=isNew?'Pick a scheduled date to create this task.':[t.createdAt?`Created ${fmtTime(t.createdAt)}`:'',t.updatedAt?`Updated ${fmtTime(t.updatedAt)}`:'',t.completedAt?`Done ${fmtTime(t.completedAt)}`:'',t.scheduledDate?`Scheduled ${fmtDate(t.scheduledDate)}`:''].filter(Boolean).join(' · ');document.querySelectorAll('.priority-pill').forEach(p=>p.classList.toggle('active',p.dataset.p===pendingPriority));buildDayPicker();renderModalActions(t);$('modalOverlay')?.classList.add('open')}
function closeModal(){activeTaskId=null;$('modalOverlay')?.classList.remove('open');closeTagDropdown()}
function renderModalActions(t){const el=$('modalActions');if(!el)return;if(t.id==='__new__'){el.innerHTML='';return}el.innerHTML=`<button class="btn-cancel" type="button" id="modalArchiveBtn">Archive</button><button class="btn-cancel" type="button" id="modalBlockBtn">${t.blocked?'Unblock':'Block'}</button><button class="btn-cancel" type="button" id="modalDeleteBtn" style="color:#ff8a8a;border-color:#5c1f1f">Delete</button>`;$('modalArchiveBtn')?.addEventListener('click',()=>modalArchiveTask(t.id));$('modalBlockBtn')?.addEventListener('click',()=>modalToggleBlocked(t.id));$('modalDeleteBtn')?.addEventListener('click',()=>modalDeleteTask(t.id))}
function selectPriority(p){pendingPriority=p;document.querySelectorAll('.priority-pill').forEach(x=>x.classList.toggle('active',x.dataset.p===p))}
function buildDayPicker(){const grid=$('dayPickerGrid');if(!grid)return;const opts=[];for(let i=0;i<10;i+=1){const d=new Date();d.setDate(d.getDate()+i);opts.push({key:key(d),day:d.toLocaleDateString(undefined,{weekday:'short'}),date:d.toLocaleDateString(undefined,{month:'short',day:'numeric'}),today:i===0})}grid.innerHTML=opts.map(o=>`<button class="day-pill ${o.key===pendingScheduleDate?'active':''} ${o.today?'today-pill':''}" type="button" data-day-key="${esc(o.key)}"><span class="pill-day">${esc(o.day)}</span><span class="pill-date">${esc(o.date)}</span></button>`).join('');grid.querySelectorAll('[data-day-key]').forEach(b=>b.addEventListener('click',()=>selectDay(b.dataset.dayKey||'')))}
function selectDay(v){pendingScheduleDate=v;buildDayPicker()}
function tags(){const map=new Map();[...tasks,...archiveData].forEach(t=>{const tag=(t.tag||'').trim();if(tag)map.set(tag,(map.get(tag)||0)+1)});return[...map.entries()].sort((a,b)=>b[1]-a[1])}
function onTagInput(v){const d=$('tagDropdown');if(!d)return;const term=(v||'').trim().toLowerCase();const list=tags().filter(([t])=>t.toLowerCase().includes(term)).slice(0,6);if(!term||!list.length){d.style.display='none';d.innerHTML='';tagHighlightIndex=-1;return}d.innerHTML=list.map(([t,c])=>`<button class="tag-option" type="button" data-tag="${esc(t)}"><span>#${esc(t)}</span><span class="tag-option-count">${c} task${c===1?'':'s'}</span></button>`).join('');d.style.display='block';tagHighlightIndex=-1;d.querySelectorAll('.tag-option').forEach(o=>o.addEventListener('click',()=>selectTagOption(o.dataset.tag||'')))}
function selectTagOption(tag){$('tagInput').value=tag;closeTagDropdown()}
function closeTagDropdown(){const d=$('tagDropdown');if(!d)return;d.style.display='none';d.innerHTML='';tagHighlightIndex=-1}
function onTagKeydown(e){const d=$('tagDropdown');if(!d||d.style.display==='none')return;const opts=[...d.querySelectorAll('.tag-option')];if(e.key==='ArrowDown'){e.preventDefault();tagHighlightIndex=Math.min(tagHighlightIndex+1,opts.length-1)}else if(e.key==='ArrowUp'){e.preventDefault();tagHighlightIndex=Math.max(tagHighlightIndex-1,-1)}else if(e.key==='Enter'&&tagHighlightIndex>=0){e.preventDefault();const t=opts[tagHighlightIndex]?.dataset.tag;if(t)selectTagOption(t)}else if(e.key==='Escape'){closeTagDropdown()}opts.forEach((o,i)=>o.classList.toggle('highlighted',i===tagHighlightIndex))}
function mutateTask(t,patch){const next={...t,...patch,updatedAt:now()};if(next.blocked){next.done=false;next.completedAt=null}return next}
async function saveModal(){if(!cloud('save task changes'))return;const text=$('modalTitleInput').value.trim();if(!text){indicator('Task title is required','warn');return}if(!pendingScheduleDate){indicator('Choose a date before saving','warn');return}if(activeTaskId==='__new__'){const stamp=now();const created={id:id(),userId:user.id,ownerEmail:user.email||'',text,category:newTaskCat,done:false,blocked:false,priority:pendingPriority,scheduledDate:pendingScheduleDate,notes:$('notesArea').value.trim(),createdAt:stamp,completedAt:null,updatedAt:stamp,tag:$('tagInput').value.trim(),archivedAt:null,archivedDate:'',deletedAt:null};tasks=[created,...tasks].sort(cmp);$('taskInput').value='';render();closeModal();try{await upsertRows([created]);await refreshFromCloud('add')}catch(error){handleCloudError(error)}return}const t=tasks.find(x=>x.id===activeTaskId);if(!t)return;const updated=mutateTask(t,{text,notes:$('notesArea').value.trim(),tag:$('tagInput').value.trim(),priority:pendingPriority,scheduledDate:pendingScheduleDate});tasks=tasks.map(x=>x.id===updated.id?updated:x);render();closeModal();try{await upsertRows([updated]);await refreshFromCloud('save')}catch(error){handleCloudError(error)}}
async function addTask(){if(!cloud('add tasks'))return;const text=$('taskInput').value.trim();if(!text){indicator('Type a task first','warn');return}openModal('__new__')}
async function toggleTask(taskId){if(!cloud('update tasks'))return;const t=tasks.find(x=>x.id===taskId);if(!t)return;const stamp=now();const updated=mutateTask(t,{done:!t.done,blocked:false,completedAt:!t.done?stamp:null});if(updated.done&&prefs().autoArchive){updated.archivedAt=stamp;updated.archivedDate=key(updated.completedAt||stamp)}tasks=tasks.map(x=>x.id===updated.id?updated:x).filter(x=>!updated.archivedAt||x.id!==updated.id);if(updated.archivedAt)archiveData=[updated,...archiveData];render();try{await upsertRows([updated]);await refreshFromCloud('toggle')}catch(error){handleCloudError(error)}}
async function setTaskBlockedState(taskId,blocked){if(!cloud('update tasks'))return;const t=tasks.find(x=>x.id===taskId);if(!t)return;const updated=mutateTask(t,{blocked,done:false,completedAt:null});tasks=tasks.map(x=>x.id===updated.id?updated:x);render();try{await upsertRows([updated]);await refreshFromCloud('block')}catch(error){handleCloudError(error)}}
async function archiveSingleTask(taskId){if(!cloud('archive tasks'))return;const t=tasks.find(x=>x.id===taskId);if(!t)return;const stamp=now();const updated=mutateTask(t,{archivedAt:stamp,archivedDate:t.archivedDate||key(t.completedAt||stamp)});try{await upsertRows([updated]);await refreshFromCloud('archive');closeModal()}catch(error){handleCloudError(error)}}
async function clearDone(){if(!cloud('archive completed tasks'))return;const done=tasks.filter(t=>t.done);if(!done.length)return;const stamp=now();const rows=done.map(t=>mutateTask(t,{archivedAt:stamp,archivedDate:t.archivedDate||key(t.completedAt||stamp)}));try{await upsertRows(rows);await refreshFromCloud('archive-completed')}catch(error){handleCloudError(error)}}
function askDelete(taskId){pendingDeleteId=taskId;const t=taskById(taskId);$('confirmTaskText').textContent=t?.text||'Delete task';$('confirmOverlay')?.classList.add('open')}
function closeConfirm(){pendingDeleteId=null;$('confirmOverlay')?.classList.remove('open')}
async function confirmDelete(){if(!pendingDeleteId||!cloud('delete tasks'))return;const t=taskById(pendingDeleteId);if(!t){closeConfirm();return}const updated=mutateTask(t,{deletedAt:now()});closeConfirm();closeModal();try{await upsertRows([updated]);await refreshFromCloud('delete')}catch(error){handleCloudError(error)}}
function modalArchiveTask(taskId){archiveSingleTask(taskId)}
function modalToggleBlocked(taskId){const t=tasks.find(x=>x.id===taskId);if(!t)return;setTaskBlockedState(taskId,!t.blocked);closeModal()}
function modalDeleteTask(taskId){closeModal();askDelete(taskId)}
async function restoreArchivedTask(taskId){if(!cloud('restore archived tasks'))return;const t=archiveData.find(x=>x.id===taskId);if(!t)return;const updated=mutateTask(t,{archivedAt:null,archivedDate:''});try{await upsertRows([updated]);await refreshFromCloud('restore')}catch(error){handleCloudError(error)}}
async function deleteArchivedTask(taskId){if(!cloud('delete archived tasks'))return;const t=archiveData.find(x=>x.id===taskId);if(!t)return;const updated=mutateTask(t,{deletedAt:now()});try{await upsertRows([updated]);await refreshFromCloud('archive-delete')}catch(error){handleCloudError(error)}}
async function editArchivedTaskDate(taskId){const t=archiveData.find(x=>x.id===taskId);if(!t)return;const next=window.prompt('Archive date (YYYY-MM-DD)',t.archivedDate||today());if(!next)return;if(!/^\d{4}-\d{2}-\d{2}$/.test(next)){indicator('Use YYYY-MM-DD','warn');return}const updated=mutateTask(t,{archivedDate:next});try{await upsertRows([updated]);await refreshFromCloud('archive-date')}catch(error){handleCloudError(error)}}
function renderArchive(){const body=$('archiveBody');if(!body)return;const q=($('archiveSearch')?.value||'').trim().toLowerCase();const icon=(type)=>type==='restore'?'<svg viewBox=\"0 0 24 24\"><path d=\"M9 7H5v4\"></path><path d=\"M5 11a7 7 0 1 0 2-5\"></path></svg>':type==='date'?'<svg viewBox=\"0 0 24 24\"><rect x=\"3\" y=\"5\" width=\"18\" height=\"16\" rx=\"2\"></rect><path d=\"M16 3v4M8 3v4M3 11h18\"></path></svg>':'<svg viewBox=\"0 0 24 24\"><path d=\"M4 7h16\"></path><path d=\"M10 11v6M14 11v6\"></path><path d=\"M6 7l1 13h10l1-13\"></path><path d=\"M9 7V4h6v3\"></path></svg>';const list=archiveData.filter(t=>!q||t.text.toLowerCase().includes(q)||(t.tag||'').toLowerCase().includes(q));if(!list.length){body.innerHTML='<div class=\"empty\" style=\"display:block;padding:24px 0\">No archived tasks yet.</div>';return}body.innerHTML=list.map(t=>`<div class=\"archive-item\"><div class=\"archive-item-row\"><div class=\"task-body\"><div class=\"task-text\">${esc(t.text)}</div><div class=\"task-meta\"><span class=\"cat-badge ${esc(t.category)}\">${esc(t.category)}</span><span class=\"priority-badge ${esc(t.priority)}\">${esc(t.priority)}</span><span class=\"task-tag-badge\">${esc(t.archivedDate||fmtDate(key(t.archivedAt||t.updatedAt)))}</span></div></div><div class=\"archive-item-actions\"><button class=\"archive-action-btn\" type=\"button\" data-archive-action=\"restore\" data-task-id=\"${esc(t.id)}\" title=\"Restore\">${icon('restore')}</button><button class=\"archive-action-btn\" type=\"button\" data-archive-action=\"date\" data-task-id=\"${esc(t.id)}\" title=\"Edit date\">${icon('date')}</button><button class=\"archive-action-btn delete\" type=\"button\" data-archive-action=\"delete\" data-task-id=\"${esc(t.id)}\" title=\"Delete\">${icon('delete')}</button></div></div></div>`).join('');body.querySelectorAll('[data-archive-action]').forEach(b=>b.addEventListener('click',()=>{const taskId=b.dataset.taskId||'';const action=b.dataset.archiveAction;if(action==='restore')restoreArchivedTask(taskId);if(action==='date')editArchivedTaskDate(taskId);if(action==='delete')deleteArchivedTask(taskId)}))}
function closeActionMenu(){$('actionOverlay')?.classList.remove('open')}
function handleActionOverlayClick(e){if(e.target?.id==='actionOverlay')closeActionMenu()}
function openArchiveMenu(){}
function monthStats(){const map=new Map();tasks.forEach(t=>{if(!t.scheduledDate)return;const cur=map.get(t.scheduledDate)||{pending:0,done:0};t.done?cur.done+=1:cur.pending+=1;map.set(t.scheduledDate,cur)});archiveData.forEach(t=>{const k=t.archivedDate||key(t.completedAt||t.archivedAt||t.updatedAt);if(!k)return;const cur=map.get(k)||{pending:0,done:0};cur.done+=1;map.set(k,cur)});return map}
function changeCalMonth(delta){calAnchor=new Date(calAnchor.getFullYear(),calAnchor.getMonth()+delta,1);renderCalendar()}
function renderCalendar(){const grid=$('calGrid'),title=$('calTitle');if(!grid||!title)return;const year=calAnchor.getFullYear(),month=calAnchor.getMonth();title.textContent=calAnchor.toLocaleDateString(undefined,{month:'long',year:'numeric'});const first=new Date(year,month,1),offset=first.getDay(),daysInMonth=new Date(year,month+1,0).getDate(),stats=monthStats();const cells=[];for(let i=0;i<offset;i+=1)cells.push('<div class="cal-day empty"></div>');for(let day=1;day<=daysInMonth;day+=1){const k=key(new Date(year,month,day)),entry=stats.get(k)||{pending:0,done:0},classes=['cal-day'];if(k===today())classes.push('today');if(entry.done)classes.push('has-done');if(entry.pending)classes.push('has-pending');cells.push(`<div class="${classes.join(' ')}"><div class="cal-day-num">${day}</div><div class="cal-day-dots">${entry.done?'<span class="cal-legend-dot done"></span>':''}${entry.pending?'<span class="cal-legend-dot pending"></span>':''}</div></div>`)}grid.innerHTML=cells.join('')}
function handleCalOverlayClick(e){if(e.target?.id==='calOverlay')toggleCalendar(false)}
function handleArchiveOverlayClick(e){if(e.target?.id==='archiveOverlay')toggleArchive(false)}
function handleOverlayClick(e){if(e.target?.id==='modalOverlay')closeModal()}
function clearGesture(){if(!gesture)return;gesture.item.style.transform='';gesture.item.classList.remove('swipe-right','swipe-left');gesture=null}
function swipe(taskId,dx){if(dx>=72){ignoreTaskTapUntil=now()+250;toggleTask(taskId);return true}if(dx<=-72){ignoreTaskTapUntil=now()+250;askDelete(taskId);return true}return false}
function onItemPointerDown(e){const item=e.currentTarget;gesture={item,taskId:item.dataset.taskId||'',startX:e.clientX,startY:e.clientY,dx:0,dy:0}}
function onItemPointerMove(e){if(!gesture||gesture.item!==e.currentTarget)return;gesture.dx=e.clientX-gesture.startX;gesture.dy=e.clientY-gesture.startY;if(Math.abs(gesture.dx)>Math.abs(gesture.dy)&&Math.abs(gesture.dx)>8){e.preventDefault();gesture.item.style.transform=`translateX(${Math.max(-96,Math.min(96,gesture.dx))}px)`;gesture.item.classList.toggle('swipe-right',gesture.dx>18);gesture.item.classList.toggle('swipe-left',gesture.dx<-18)}}
function onItemPointerUp(e){if(!gesture||gesture.item!==e.currentTarget)return;const {taskId,dx,dy}=gesture;const moved=Math.abs(dx)>8||Math.abs(dy)>8;const handled=moved&&swipe(taskId,dx);clearGesture();if(!handled&&!moved&&now()>ignoreTaskTapUntil)openModal(taskId)}
function onItemPointerCancel(){clearGesture()}
function bindTaskItems(){document.querySelectorAll('.task-item[data-task-id]').forEach(item=>{item.addEventListener('pointerdown',onItemPointerDown);item.addEventListener('pointermove',onItemPointerMove);item.addEventListener('pointerup',onItemPointerUp);item.addEventListener('pointercancel',onItemPointerCancel)})}
function checkAllDone(){return}
document.addEventListener('click',e=>{if(!e.target.closest('.tag-section'))closeTagDropdown()});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&user)refreshFromCloud('foreground').catch(handleCloudError)});
window.addEventListener('storage',e=>{if(e.key===LAST_SYNC_KEY)refreshLastSyncUI()});
document.addEventListener('touchstart',e=>{if(window.scrollY===0&&!ptrActive)ptrStartY=e.touches[0].clientY},{passive:true});
document.addEventListener('touchmove',e=>{if(!ptrStartY)return;const dy=e.touches[0].clientY-ptrStartY;if(dy>80&&window.scrollY===0){ptrActive=true;$('ptrIndicator')?.classList.add('visible')}},{passive:true});
document.addEventListener('touchend',()=>{if(!ptrActive){ptrStartY=0;return}ptrActive=false;ptrStartY=0;refreshFromCloud('pull').catch(handleCloudError).finally(()=>setTimeout(()=>$('ptrIndicator')?.classList.remove('visible'),500))});
window.addEventListener('load',async()=>{$('proxyUrlInput').value=localStorage.getItem(PROXY_KEY)||'';$('sortSelect').value=sortMode;$('statusSelect').value=filter;$('taskInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')addTask()});$('archiveSearch')?.addEventListener('input',renderArchive);initAIStatus();disableNonCoreFeatures();renderWorkflowSettings();initATH();refreshLastSyncUI();render();renderCalendar();renderSyncSettings();schedulePeriodicSync();if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}await initSupabaseSync()});

